export const kepIcons = {
  learn: 'mdi:school-outline',
  course: 'mdi:book-open-page-variant-outline',
  courses: 'mdi:book-open-variant-outline',
  blog: 'mdi:notebook-outline',
  test: 'mdi:clipboard-check-outline',
  tests: 'mdi:clipboard-check-outline',
  challenge: 'mdi:lightning-bolt-outline',
  challenges: 'mdi:lightning-bolt-outline',
  problem: 'mdi:code-tags',
  problems: 'mdi:code-tags',
  project: 'mdi:briefcase-outline',
  projects: 'mdi:briefcase-outline',
  practice: 'mdi:puzzle-outline',
  competition: 'mdi:trophy-outline',
  competitions: 'mdi:trophy-outline',
  tournament: 'mdi:medal-outline',
  tournaments: 'mdi:medal-outline',
  arena: 'mdi:shield-outline',
  contest: 'mdi:flag-outline',
  contests: 'mdi:flag-outline',
  hackathon: 'mdi:rocket-outline',
  hackathons: 'mdi:rocket-outline',
  duels: 'mdi:sword-cross',
  duel: 'mdi:sword-cross',
  users: 'mdi:account-multiple-outline',
  todo: 'mdi:format-list-checks',
  profile: 'mdi:account-circle-outline',
  statistics: 'mdi:chart-pie-outline',
  rating: 'mdi:chart-line-variant',
  calendar: 'mdi:calendar-outline',
  clock: 'mdi:clock-outline',
  attempt: 'mdi:target',
  attempts: 'mdi:target',
  'rating-changes': 'mdi:chart-timeline-variant',
  timer: 'mdi:timer-outline',
  eye: 'mdi:eye-outline',
  question: 'mdi:help-circle-outline',
  verdict: 'mdi:checkbox-marked-circle-outline',
  lang: 'mdi:translate',
  'challenge-time': 'mdi:clock-outline',
  'challenge-task': 'mdi:clipboard-text-outline',
  username: 'mdi:account-edit-outline',
  streak: 'mdi:fire',
  tags: 'mdi:tag-multiple-outline',
  difficulty: 'mdi:speedometer',
  login: 'mdi:login',
} as const;

export type KepIconName = keyof typeof kepIcons;

export const getKepIcon = (name: KepIconName) => kepIcons[name];
