export const keenIcons = {
  learn: 'teacher',
  course: 'book-open',
  courses: 'book-open',
  blog: 'note-2',
  test: 'tablet-ok',
  tests: 'tablet-ok',
  challenge: 'abstract-22',
  challenges: 'abstract-22',
  problem: 'message-programming',
  problems: 'message-programming',
  project: 'technology-2',
  projects: 'technology-2',
  practice: 'abstract-45',
  competition: 'cup',
  competitions: 'cup',
  tournament: 'award',
  tournaments: 'award',
  arena: 'shield',
  contest: 'flag',
  contests: 'flag',
  hackathon: 'abstract-3',
  hackathons: 'abstract-3',
  duels: 'abstract-21',
  duel: 'abstract-21',
  users: 'profile-user',
  todo: 'check-square',

  profile: 'user-tick',
  statistics: 'chart-pie-simple',
  rating: 'chart-simple-2',
  attempt: 'filter-tick',
  attempts: 'filter-tick',
  'rating-changes': 'chart-line-up',
  question: 'question-2',
  verdict: 'double-check',
  lang: 'message-programming',

  'challenge-time': 'watch',
  'challenge-task': 'abstract-45',

  username: 'user-edit',
  streak: 'calendar-tick',

  tags: 'data',
  difficulty: 'graph-2',

  login: 'exit-left',
};

export const featherIcons = {
  like: 'heart',
  learn: 'book',
  course: 'book-open',
  lugavar: 'bookmark',
  practice: 'edit',
  competitions: 'zap',
  users: 'users',
  home: 'home',
  challenge: 'zap',
  arena: 'shield',
  tournament: 'award',
  test: 'edit-3',
  help: 'help-circle',
  help_project: 'git-pull-request',
  user: 'user',
  comment: 'message-circle',
  view: 'eye',
  exists: 'check-circle',
  not_exists: 'x-circle',
  problem: 'align-justify',
  submit: 'send',
  attempt: 'sliders',
  rating: 'bar-chart',
  custom_test: 'terminal',
  contest: 'flag',
  delta: 'triangle',
  question: 'help-circle',
  project: 'slack',
  achievement: 'award',
  hack: 'unlock'
};
