export enum AttemptLangs {
  PYTHON = 'py',
  CPP = 'cpp',
  R = 'r',
  HASKELL = 'hs',
  KEP = 'kep',
  C = 'c',
  KOTLIN = 'kt',
  TEXT = 'text',
  HTML = 'html',
  SQL = 'sql',
  BASH = 'bash',
  JS = 'js',
  PHP = 'php',
  CSHARP = 'cs',
  JAVA = 'java',
  RUST = 'rs',
  TS = 'ts',
}
