export const devIcons = [
  'devicon-openal-plain',
  'devicon-kaggle-original-wordmark',
  'devicon-kaggle-plain-wordmark',
  'devicon-kaggle-original',
  'devicon-kaggle-plain',
  'devicon-pytest-plain-wordmark',
  'devicon-pytest-plain',
  'devicon-fastapi-plain-wordmark',
  'devicon-fastapi-plain',
  'devicon-opencv-plain-wordmark',
  'devicon-opencv-plain',
  'devicon-k3s-plain-wordmark',
  'devicon-k3s-original',
  'devicon-k3s-plain',
  'devicon-packer-original-wordmark',
  'devicon-packer-plain-wordmark',
  'devicon-packer-original',
  'devicon-packer-plain',
  'devicon-anaconda-original-wordmark',
  'devicon-anaconda-plain-wordmark',
  'devicon-anaconda-original',
  'devicon-anaconda-plain',
  'devicon-prometheus-original-wordmark',
  'devicon-prometheus-original',
  'devicon-rspec-original-wordmark',
  'devicon-rspec-plain-wordmark',
  'devicon-rspec-original',
  'devicon-rspec-plain',
  'devicon-argocd-plain-wordmark',
  'devicon-argocd-plain',
  'devicon-blender-original-wordmark',
  'devicon-blender-original',
  'devicon-jetbrains-plain',
  'devicon-cmake-plain-wordmark',
  'devicon-cmake-plain',
  'devicon-dropwizard-plain',
  'devicon-nuget-original-wordmark',
  'devicon-nuget-original',
  'devicon-podman-plain-wordmark',
  'devicon-podman-plain',
  'devicon-networkx-original',
  'devicon-sqlite-plain-wordmark',
  'devicon-sqlite-plain',
  'devicon-discordjs-plain-wordmark',
  'devicon-discordjs-plain',
  'devicon-unrealengine-original-wordmark',
  'devicon-unrealengine-plain-wordmark',
  'devicon-unrealengine-original',
  'devicon-unrealengine-plain',
  'devicon-django-plain-wordmark',
  'devicon-django-plain',
  'devicon-devicon-line-wordmark',
  'devicon-devicon-line',
  'devicon-devicon-plain-wordmark',
  'devicon-devicon-plain',
  'devicon-bootstrap-plain-wordmark',
  'devicon-bootstrap-plain',
  'devicon-solidity-plain',
  'devicon-polygon-plain',
  'devicon-maya-plain-wordmark',
  'devicon-maya-plain',
  'devicon-xcode-plain',
  'devicon-selenium-original',
  'devicon-selenium-plain',
  'devicon-ifttt-original',
  'devicon-ifttt-plain',
  'devicon-pytorch-plain-wordmark',
  'devicon-pytorch-original',
  'devicon-pytorch-plain',
  'devicon-xamarin-original-wordmark',
  'devicon-xamarin-plain-wordmark',
  'devicon-xamarin-original',
  'devicon-xamarin-plain',
  'devicon-hugo-plain-wordmark',
  'devicon-hugo-plain',
  'devicon-grafana-original-wordmark',
  'devicon-grafana-plain-wordmark',
  'devicon-grafana-original',
  'devicon-grafana-plain',
  'devicon-ansible-plain-wordmark',
  'devicon-ansible-plain',
  'devicon-shotgrid-original-wordmark',
  'devicon-shotgrid-plain-wordmark',
  'devicon-shotgrid-plain',
  'devicon-androidstudio-plain-wordmark',
  'devicon-androidstudio-plain',
  'devicon-eslint-original-wordmark',
  'devicon-eslint-plain-wordmark',
  'devicon-eslint-original',
  'devicon-eslint-plain',
  'devicon-latex-original',
  'devicon-latex-plain',
  'devicon-vuetify-plain',
  'devicon-vuetify-line',
  'devicon-sdl-plain',
  'devicon-bitbucket-original-wordmark',
  'devicon-bitbucket-plain-wordmark',
  'devicon-bitbucket-original',
  'devicon-bitbucket-plain',
  'devicon-confluence-original-wordmark',
  'devicon-confluence-plain-wordmark',
  'devicon-confluence-original',
  'devicon-confluence-plain',
  'devicon-fedora-plain',
  'devicon-rect-plain',
  'devicon-bamboo-original-wordmark',
  'devicon-bamboo-plain-wordmark',
  'devicon-bamboo-original',
  'devicon-bamboo-plain',
  'devicon-jira-plain-wordmark',
  'devicon-jira-plain',
  'devicon-terraform-plain-wordmark',
  'devicon-terraform-plain',
  'devicon-webflow-original',
  'devicon-gentoo-plain',
  'devicon-gentoo-plain-wordmark',
  'devicon-opensuse-plain-wordmark',
  'devicon-opensuse-plain',
  'devicon-storybook-plain-wordmark',
  'devicon-storybook-plain',
  'devicon-pandas-original-wordmark',
  'devicon-pandas-plain-wordmark',
  'devicon-pandas-original',
  'devicon-pandas-plain',
  'devicon-centos-plain-wordmark',
  'devicon-centos-plain',
  'devicon-azure-plain-wordmark',
  'devicon-azure-plain',
  'devicon-go-line',
  'devicon-go-plain',
  'devicon-go-original-wordmark',
  'devicon-go-plain-wordmark',
  'devicon-msdos-line',
  'devicon-arduino-plain-wordmark',
  'devicon-arduino-plain',
  'devicon-qt-original',
  'devicon-qt-plain',
  'devicon-gcc-plain',
  'devicon-svelte-plain-wordmark',
  'devicon-svelte-plain',
  'devicon-slack-plain-wordmark',
  'devicon-slack-plain',
  'devicon-canva-original',
  'devicon-canva-plain',
  'devicon-jamstack-plain-wordmark',
  'devicon-jamstack-original',
  'devicon-jamstack-plain',
  'devicon-denojs-original-wordmark',
  'devicon-denojs-plain-wordmark',
  'devicon-denojs-original',
  'devicon-denojs-plain',
  'devicon-apachekafka-original-wordmark',
  'devicon-apachekafka-plain-wordmark',
  'devicon-apachekafka-original',
  'devicon-apachekafka-plain',
  'devicon-filezilla-plain-wordmark',
  'devicon-filezilla-plain',
  'devicon-opengl-plain',
  'devicon-putty-plain',
  'devicon-opera-plain-wordmark',
  'devicon-opera-plain',
  'devicon-subversion-original',
  'devicon-subversion-plain',
  'devicon-tortoisegit-line',
  'devicon-tortoisegit-plain',
  'devicon-towergit-plain-wordmark',
  'devicon-towergit-plain',
  'devicon-unity-original-wordmark',
  'devicon-unity-original',
  'devicon-neo4j-plain-wordmark',
  'devicon-neo4j-plain',
  'devicon-nuxtjs-plain-wordmark',
  'devicon-nuxtjs-plain',
  'devicon-socketio-original-wordmark',
  'devicon-socketio-plain-wordmark',
  'devicon-socketio-original',
  'devicon-socketio-plain',
  'devicon-processing-plain-wordmark',
  'devicon-processing-plain',
  'devicon-feathersjs-original',
  'devicon-adonisjs-original-wordmark',
  'devicon-adonisjs-plain-wordmark',
  'devicon-adonisjs-original',
  'devicon-adonisjs-plain',
  'devicon-numpy-original-wordmark',
  'devicon-numpy-original',
  'devicon-numpy-plain',
  'devicon-matlab-line',
  'devicon-matlab-plain',
  'devicon-clojurescript-plain',
  'devicon-threejs-original-wordmark',
  'devicon-threejs-original',
  'devicon-markdown-original',
  'devicon-markdown-plain',
  'devicon-nixos-plain-wordmark',
  'devicon-nixos-plain',
  'devicon-perl-plain',
  'devicon-tensorflow-line-wordmark',
  'devicon-tensorflow-line',
  'devicon-tensorflow-original-wordmark',
  'devicon-tensorflow-original',
  'devicon-zig-plain-wordmark',
  'devicon-zig-original',
  'devicon-zig-plain',
  'devicon-raspberrypi-line-wordmark',
  'devicon-raspberrypi-line',
  'devicon-embeddedc-plain-wordmark',
  'devicon-embeddedc-plain',
  'devicon-labview-plain-wordmark',
  'devicon-labview-plain',
  'devicon-modx-plain-wordmark',
  'devicon-modx-plain',
  'devicon-knockout-plain-wordmark',
  'devicon-rstudio-plain',
  'devicon-phalcon-plain',
  'devicon-minitab-plain',
  'devicon-bulma-plain',
  'devicon-spss-plain',
  'devicon-karma-plain',
  'devicon-jest-plain',
  'devicon-circleci-plain-wordmark',
  'devicon-circleci-plain',
  'devicon-codecov-plain',
  'devicon-magento-line',
  'devicon-magento-original-wordmark',
  'devicon-magento-original',
  'devicon-shopware-original-wordmark',
  'devicon-shopware-original',
  'devicon-salesforce-plain',
  'devicon-vuestorefront-plain',
  'devicon-unix-original',
  'devicon-godot-plain-wordmark',
  'devicon-godot-plain',
  'devicon-vscode-plain-wordmark',
  'devicon-vscode-plain',
  'devicon-julia-plain-wordmark',
  'devicon-julia-plain',
  'devicon-crystal-original-wordmark',
  'devicon-crystal-original',
  'devicon-tailwindcss-plain',
  'devicon-tailwindcss-original-wordmark',
  'devicon-weblate-plain-wordmark',
  'devicon-weblate-plain',
  'devicon-thealgorithms-plain-wordmark',
  'devicon-thealgorithms-plain',
  'devicon-spring-plain-wordmark',
  'devicon-spring-plain',
  'devicon-rails-plain-wordmark',
  'devicon-rails-plain',
  'devicon-phoenix-plain-wordmark',
  'devicon-phoenix-plain',
  'devicon-nextjs-original-wordmark',
  'devicon-nextjs-plain-wordmark',
  'devicon-nextjs-line',
  'devicon-nextjs-original',
  'devicon-nextjs-plain',
  'devicon-lua-plain-wordmark',
  'devicon-lua-plain',
  'devicon-graphql-plain-wordmark',
  'devicon-graphql-plain',
  'devicon-gitter-plain-wordmark',
  'devicon-gitter-plain',
  'devicon-figma-plain',
  'devicon-digitalocean-plain-wordmark',
  'devicon-digitalocean-plain',
  'devicon-dotnetcore-plain',
  'devicon-dart-plain-wordmark',
  'devicon-dart-plain',
  'devicon-r-plain',
  'devicon-r-original',
  'devicon-ocaml-plain-wordmark',
  'devicon-ocaml-plain',
  'devicon-jupyter-plain-wordmark',
  'devicon-jupyter-plain',
  'devicon-fsharp-plain',
  'devicon-elixir-plain-wordmark',
  'devicon-elixir-plain',
  'devicon-aarch64-plain',
  'devicon-xd-line',
  'devicon-xd-plain',
  'devicon-uwsgi-plain',
  'devicon-microsoftsqlserver-plain-wordmark',
  'devicon-microsoftsqlserver-plain',
  'devicon-sqlalchemy-original-wordmark',
  'devicon-sqlalchemy-plain-wordmark',
  'devicon-sqlalchemy-plain',
  'devicon-rocksdb-plain',
  'devicon-objectivec-plain',
  'devicon-kubernetes-plain-wordmark',
  'devicon-kubernetes-plain',
  'devicon-googlecloud-plain-wordmark',
  'devicon-googlecloud-plain',
  'devicon-flask-original-wordmark',
  'devicon-flask-plain-wordmark',
  'devicon-flask-original',
  'devicon-flask-plain',
  'devicon-firebase-plain-wordmark',
  'devicon-firebase-plain',
  'devicon-eleventy-plain',
  'devicon-appwrite-plain-wordmark',
  'devicon-appwrite-original-wordmark',
  'devicon-appwrite-plain',
  'devicon-appwrite-original',
  'devicon-bash-plain',
  'devicon-woocommerce-plain-wordmark',
  'devicon-woocommerce-plain',
  'devicon-typo3-plain-wordmark',
  'devicon-typo3-plain',
  'devicon-premierepro-plain',
  'devicon-nestjs-plain-wordmark',
  'devicon-nestjs-plain',
  'devicon-materialui-plain',
  'devicon-kotlin-plain-wordmark',
  'devicon-kotlin-plain',
  'devicon-jenkins-plain',
  'devicon-jenkins-line',
  'devicon-haxe-plain',
  'devicon-gatsby-plain-wordmark',
  'devicon-gatsby-plain',
  'devicon-flutter-plain',
  'devicon-composer-line-wordmark',
  'devicon-composer-plain-wordmark',
  'devicon-composer-line',
  'devicon-composer-plain',
  'devicon-aftereffects-plain',
  'devicon-yunohost-plain',
  'devicon-redux-original',
  'devicon-redux-plain',
  'devicon-clojure-line',
  'devicon-clojure-plain',
  'devicon-mocha-plain',
  'devicon-haskell-plain',
  'devicon-haskell-plain-wordmark',
  'devicon-codepen-original-wordmark',
  'devicon-codepen-plain',
  'devicon-codepen-original',
  'devicon-groovy-plain',
  'devicon-rust-plain',
  'devicon-scala-plain-wordmark',
  'devicon-scala-plain',
  'devicon-grails-plain',
  'devicon-sketch-line-wordmark',
  'devicon-sketch-line',
  'devicon-npm-original-wordmark',
  'devicon-ionic-original-wordmark',
  'devicon-ionic-original',
  'devicon-ember-original-wordmark',
  'devicon-ember-plain-wordmark',
  'devicon-electron-original-wordmark',
  'devicon-electron-original',
  'devicon-vagrant-plain-wordmark',
  'devicon-vagrant-plain',
  'devicon-yarn-plain-wordmark',
  'devicon-yarn-plain',
  'devicon-handlebars-plain-wordmark',
  'devicon-handlebars-plain',
  'devicon-couchdb-plain-wordmark',
  'devicon-couchdb-plain',
  'devicon-behance-plain-wordmark',
  'devicon-behance-plain',
  'devicon-linkedin-plain-wordmark',
  'devicon-linkedin-plain',
  'devicon-ceylon-plain',
  'devicon-elm-plain-wordmark',
  'devicon-elm-plain',
  'devicon-cakephp-plain-wordmark',
  'devicon-cakephp-plain',
  'devicon-stylus-original',
  'devicon-express-original-wordmark',
  'devicon-express-original',
  'devicon-intellij-plain-wordmark',
  'devicon-intellij-plain',
  'devicon-pycharm-plain-wordmark',
  'devicon-pycharm-plain',
  'devicon-rubymine-plain-wordmark',
  'devicon-rubymine-plain',
  'devicon-webstorm-plain-wordmark',
  'devicon-webstorm-plain',
  'devicon-tomcat-line-wordmark',
  'devicon-tomcat-line',
  'devicon-vuejs-line-wordmark',
  'devicon-vuejs-line',
  'devicon-vuejs-plain-wordmark',
  'devicon-vuejs-plain',
  'devicon-swift-plain-wordmark',
  'devicon-swift-plain',
  'devicon-webpack-plain-wordmark',
  'devicon-webpack-plain',
  'devicon-visualstudio-plain-wordmark',
  'devicon-visualstudio-plain',
  'devicon-sequelize-plain-wordmark',
  'devicon-sequelize-plain',
  'devicon-typescript-plain',
  'devicon-typescript-original',
  'devicon-babel-plain',
  'devicon-babel-original',
  'devicon-facebook-plain',
  'devicon-facebook-original',
  'devicon-google-plain-wordmark',
  'devicon-google-original-wordmark',
  'devicon-google-plain',
  'devicon-google-original',
  'devicon-twitter-original',
  'devicon-twitter-plain',
  'devicon-mocha',
  'devicon-jasmine-plain',
  'devicon-jasmine-wordmark',
  'devicon-gatling-plain',
  'devicon-gatling-plain-wordmark',
  'devicon-phpstorm-plain',
  'devicon-phpstorm-plain-wordmark',
  'devicon-sourcetree-original',
  'devicon-sourcetree-plain',
  'devicon-sourcetree-original-wordmark',
  'devicon-sourcetree-plain-wordmark',
  'devicon-ssh-original',
  'devicon-ssh-plain',
  'devicon-ssh-original-wordmark',
  'devicon-ssh-plain-wordmark',
  'devicon-jeet-plain',
  'devicon-jeet-plain-wordmark',
  'devicon-gitlab-plain',
  'devicon-gitlab-plain-wordmark',
  'devicon-github-original',
  'devicon-github-plain',
  'devicon-github-original-wordmark',
  'devicon-d3js-plain',
  'devicon-d3js-original',
  'devicon-gradle-plain',
  'devicon-gradle-plain-wordmark',
  'devicon-cucumber-plain',
  'devicon-cucumber-plain-wordmark',
  'devicon-protractor-plain',
  'devicon-protractor-plain-wordmark',
  'devicon-safari-line-wordmark',
  'devicon-safari-line',
  'devicon-safari-plain-wordmark',
  'devicon-safari-plain',
  'devicon-gimp-plain',
  'devicon-redhat-plain-wordmark',
  'devicon-redhat-plain',
  'devicon-cplusplus-line',
  'devicon-cplusplus-line-wordmark',
  'devicon-cplusplus-plain',
  'devicon-cplusplus-plain-wordmark',
  'devicon-csharp-line',
  'devicon-csharp-line-wordmark',
  'devicon-csharp-plain',
  'devicon-csharp-plain-wordmark',
  'devicon-c-line',
  'devicon-c-line-wordmark',
  'devicon-c-plain',
  'devicon-c-plain-wordmark',
  'devicon-nodewebkit-line-wordmark',
  'devicon-nodewebkit-line',
  'devicon-nodewebkit-plain-wordmark',
  'devicon-nodewebkit-plain',
  'devicon-nginx-original',
  'devicon-nginx-original-wordmark',
  'devicon-nginx-plain',
  'devicon-nginx-plain-wordmark',
  'devicon-erlang-plain-wordmark',
  'devicon-erlang-plain',
  'devicon-doctrine-line-wordmark',
  'devicon-doctrine-line',
  'devicon-doctrine-plain-wordmark',
  'devicon-doctrine-plain',
  'devicon-apache-line-wordmark',
  'devicon-apache-line',
  'devicon-apache-plain-wordmark',
  'devicon-apache-plain',
  'devicon-redis-plain-wordmark',
  'devicon-redis-plain',
  'devicon-meteor-plain-wordmark',
  'devicon-meteor-plain',
  'devicon-heroku-line-wordmark',
  'devicon-heroku-original-wordmark',
  'devicon-heroku-line',
  'devicon-heroku-original',
  'devicon-heroku-plain-wordmark',
  'devicon-heroku-plain',
  'devicon-docker-plain-wordmark',
  'devicon-docker-plain',
  'devicon-symfony-original-wordmark',
  'devicon-symfony-plain-wordmark',
  'devicon-symfony-original',
  'devicon-symfony-plain',
  'devicon-react-original-wordmark',
  'devicon-react-plain-wordmark',
  'devicon-react-original',
  'devicon-react-plain',
  'devicon-amazonwebservices-original',
  'devicon-amazonwebservices-plain',
  'devicon-amazonwebservices-plain-wordmark',
  'devicon-android-plain-wordmark',
  'devicon-android-plain',
  'devicon-angularjs-plain-wordmark',
  'devicon-angularjs-plain',
  'devicon-appcelerator-original',
  'devicon-appcelerator-plain',
  'devicon-appcelerator-plain-wordmark',
  'devicon-apple-original',
  'devicon-apple-plain',
  'devicon-atom-original-wordmark',
  'devicon-atom-plain-wordmark',
  'devicon-atom-original',
  'devicon-atom-plain',
  'devicon-backbonejs-plain-wordmark',
  'devicon-backbonejs-plain',
  'devicon-bower-line-wordmark',
  'devicon-bower-line',
  'devicon-bower-plain-wordmark',
  'devicon-bower-plain',
  'devicon-chrome-plain-wordmark',
  'devicon-chrome-plain',
  'devicon-codeigniter-plain-wordmark',
  'devicon-codeigniter-plain',
  'devicon-coffeescript-original-wordmark',
  'devicon-coffeescript-plain-wordmark',
  'devicon-coffeescript-original',
  'devicon-coffeescript-plain',
  'devicon-css3-plain-wordmark',
  'devicon-css3-plain',
  'devicon-debian-plain-wordmark',
  'devicon-debian-plain',
  'devicon-dot-net-plain-wordmark',
  'devicon-dot-net-plain',
  'devicon-drupal-plain-wordmark',
  'devicon-drupal-plain',
  'devicon-firefox-plain-wordmark',
  'devicon-firefox-plain',
  'devicon-foundation-plain-wordmark',
  'devicon-foundation-plain',
  'devicon-git-plain-wordmark',
  'devicon-git-plain',
  'devicon-grunt-line-wordmark',
  'devicon-grunt-line',
  'devicon-grunt-plain-wordmark',
  'devicon-grunt-plain',
  'devicon-gulp-plain',
  'devicon-html5-plain-wordmark',
  'devicon-html5-plain',
  'devicon-ie10-original',
  'devicon-ie10-plain',
  'devicon-illustrator-line',
  'devicon-illustrator-plain',
  'devicon-inkscape-plain-wordmark',
  'devicon-inkscape-plain',
  'devicon-java-plain-wordmark',
  'devicon-java-plain',
  'devicon-javascript-plain',
  'devicon-jquery-plain-wordmark',
  'devicon-jquery-plain',
  'devicon-krakenjs-plain-wordmark',
  'devicon-krakenjs-plain',
  'devicon-laravel-plain-wordmark',
  'devicon-laravel-plain',
  'devicon-less-plain-wordmark',
  'devicon-linux-plain',
  'devicon-mongodb-plain-wordmark',
  'devicon-mongodb-plain',
  'devicon-moodle-plain-wordmark',
  'devicon-moodle-plain',
  'devicon-mysql-plain-wordmark',
  'devicon-mysql-plain',
  'devicon-nodejs-plain-wordmark',
  'devicon-nodejs-plain',
  'devicon-oracle-original',
  'devicon-oracle-plain',
  'devicon-photoshop-line',
  'devicon-photoshop-plain',
  'devicon-php-plain',
  'devicon-postgresql-plain-wordmark',
  'devicon-postgresql-plain',
  'devicon-python-plain-wordmark',
  'devicon-python-plain',
  'devicon-ruby-plain-wordmark',
  'devicon-ruby-plain',
  'devicon-sass-original',
  'devicon-sass-plain',
  'devicon-travis-plain-wordmark',
  'devicon-travis-plain',
  'devicon-trello-plain-wordmark',
  'devicon-trello-plain',
  'devicon-ubuntu-plain-wordmark',
  'devicon-ubuntu-plain',
  'devicon-vim-plain',
  'devicon-windows8-original-wordmark',
  'devicon-windows8-plain-wordmark',
  'devicon-windows8-original',
  'devicon-windows8-plain',
  'devicon-wordpress-plain-wordmark',
  'devicon-wordpress-plain',
  'devicon-yii-plain-wordmark',
  'devicon-yii-plain',
  'devicon-zend-plain-wordmark',
  'devicon-zend-plain',
  'devicon-adonisjs-original colored',
  'devicon-adonisjs-original-wordmark colored',
  'devicon-adonisjs-plain colored',
  'devicon-adonisjs-plain-wordmark colored',
  'devicon-aftereffects-plain colored',
  'devicon-amazonwebservices-original colored',
  'devicon-amazonwebservices-plain-wordmark colored',
  'devicon-amazonwebservices-plain colored',
  'devicon-android-plain colored',
  'devicon-android-plain-wordmark colored',
  'devicon-androidstudio-plain colored',
  'devicon-androidstudio-plain-wordmark colored',
  'devicon-aarch64-plain colored',
  'devicon-angularjs-plain colored',
  'devicon-angularjs-plain-wordmark colored',
  'devicon-ansible-plain colored',
  'devicon-ansible-plain-wordmark colored',
  'devicon-apache-plain colored',
  'devicon-apache-plain-wordmark colored',
  'devicon-apache-line colored',
  'devicon-apache-line-wordmark colored',
  'devicon-apachekafka-original colored',
  'devicon-apachekafka-original-wordmark colored',
  'devicon-apachekafka-plain colored',
  'devicon-apachekafka-plain-wordmark colored',
  'devicon-appcelerator-original colored',
  'devicon-appcelerator-plain-wordmark colored',
  'devicon-appcelerator-plain colored',
  'devicon-apple-original colored',
  'devicon-apple-plain colored',
  'devicon-appwrite-plain colored',
  'devicon-appwrite-plain-wordmark colored',
  'devicon-appwrite-original colored',
  'devicon-appwrite-original-wordmark colored',
  'devicon-arduino-plain colored',
  'devicon-arduino-plain-wordmark colored',
  'devicon-atom-original colored',
  'devicon-atom-original-wordmark colored',
  'devicon-atom-plain colored',
  'devicon-atom-plain-wordmark colored',
  'devicon-azure-plain colored',
  'devicon-azure-plain-wordmark colored',
  'devicon-babel-plain colored',
  'devicon-babel-original colored',
  'devicon-backbonejs-plain colored',
  'devicon-backbonejs-plain-wordmark colored',
  'devicon-bamboo-original colored',
  'devicon-bamboo-original-wordmark colored',
  'devicon-bamboo-plain colored',
  'devicon-bamboo-plain-wordmark colored',
  'devicon-bash-plain colored',
  'devicon-behance-plain colored',
  'devicon-behance-plain-wordmark colored',
  'devicon-bitbucket-original colored',
  'devicon-bitbucket-original-wordmark colored',
  'devicon-bitbucket-plain colored',
  'devicon-bitbucket-plain-wordmark colored',
  'devicon-bootstrap-plain colored',
  'devicon-bootstrap-plain-wordmark colored',
  'devicon-bulma-plain colored',
  'devicon-bower-plain colored',
  'devicon-bower-plain-wordmark colored',
  'devicon-bower-line colored',
  'devicon-bower-line-wordmark colored',
  'devicon-c-plain colored',
  'devicon-c-plain-wordmark colored',
  'devicon-c-line colored',
  'devicon-c-line-wordmark colored',
  'devicon-c-plain-wordmark colored',
  'devicon-c-line-wordmark colored',
  'devicon-cakephp-plain colored',
  'devicon-cakephp-plain-wordmark colored',
  'devicon-canva-original colored',
  'devicon-canva-plain colored',
  'devicon-centos-plain colored',
  'devicon-centos-plain-wordmark colored',
  'devicon-ceylon-plain colored',
  'devicon-chrome-plain colored',
  'devicon-chrome-plain-wordmark colored',
  'devicon-circleci-plain colored',
  'devicon-circleci-plain-wordmark colored',
  'devicon-clojure-line colored',
  'devicon-clojure-plain colored',
  'devicon-clojure-plain colored',
  'devicon-cmake-plain colored',
  'devicon-cmake-plain-wordmark colored',
  'devicon-clojurescript-plain colored',
  'devicon-codecov-plain colored',
  'devicon-codeigniter-plain colored',
  'devicon-codeigniter-plain-wordmark colored',
  'devicon-codepen-plain colored',
  'devicon-codepen-plain-wordmark colored',
  'devicon-codepen-original colored',
  'devicon-coffeescript-original colored',
  'devicon-coffeescript-original-wordmark colored',
  'devicon-coffeescript-plain colored',
  'devicon-coffeescript-plain-wordmark colored',
  'devicon-composer-line colored',
  'devicon-composer-line-wordmark colored',
  'devicon-composer-plain colored',
  'devicon-composer-plain-wordmark colored',
  'devicon-confluence-original colored',
  'devicon-confluence-original-wordmark colored',
  'devicon-confluence-plain colored',
  'devicon-confluence-plain-wordmark colored',
  'devicon-couchdb-plain colored',
  'devicon-couchdb-plain-wordmark colored',
  'devicon-cplusplus-plain colored',
  'devicon-cplusplus-plain-wordmark colored',
  'devicon-cplusplus-line colored',
  'devicon-cplusplus-line-wordmark colored',
  'devicon-cplusplus-plain-wordmark colored',
  'devicon-cplusplus-line-wordmark colored',
  'devicon-csharp-plain colored',
  'devicon-csharp-plain-wordmark colored',
  'devicon-csharp-line colored',
  'devicon-csharp-line-wordmark colored',
  'devicon-csharp-plain-wordmark colored',
  'devicon-csharp-line-wordmark colored',
  'devicon-css3-plain colored',
  'devicon-css3-plain-wordmark colored',
  'devicon-cucumber-plain colored',
  'devicon-cucumber-plain-wordmark colored',
  'devicon-crystal-original colored',
  'devicon-crystal-original-wordmark colored',
  'devicon-d3js-plain colored',
  'devicon-dart-plain colored',
  'devicon-dart-plain-wordmark colored',
  'devicon-debian-plain colored',
  'devicon-debian-plain-wordmark colored',
  'devicon-denojs-original colored',
  'devicon-denojs-original-wordmark colored',
  'devicon-denojs-plain colored',
  'devicon-denojs-plain-wordmark colored',
  'devicon-devicon-plain colored',
  'devicon-devicon-plain-wordmark colored',
  'devicon-devicon-line colored',
  'devicon-devicon-line-wordmark colored',
  'devicon-django-plain colored',
  'devicon-django-plain-wordmark colored',
  'devicon-docker-plain colored',
  'devicon-docker-plain-wordmark colored',
  'devicon-doctrine-plain colored',
  'devicon-doctrine-plain-wordmark colored',
  'devicon-doctrine-line colored',
  'devicon-doctrine-line-wordmark colored',
  'devicon-dot-net-plain colored',
  'devicon-dot-net-plain-wordmark colored',
  'devicon-dotnetcore-plain colored',
  'devicon-drupal-plain colored',
  'devicon-drupal-plain-wordmark colored',
  'devicon-digitalocean-plain colored',
  'devicon-digitalocean-plain-wordmark colored',
  'devicon-discordjs-plain colored',
  'devicon-discordjs-plain-wordmark colored',
  'devicon-electron-original colored',
  'devicon-electron-original-wordmark colored',
  'devicon-eleventy-plain colored',
  'devicon-elixir-plain colored',
  'devicon-elixir-plain-wordmark colored',
  'devicon-elm-plain colored',
  'devicon-elm-plain-wordmark colored',
  'devicon-ember-original-wordmark colored',
  'devicon-ember-plain-wordmark colored',
  'devicon-embeddedc-plain colored',
  'devicon-embeddedc-plain-wordmark colored',
  'devicon-erlang-plain colored',
  'devicon-erlang-plain-wordmark colored',
  'devicon-eslint-original colored',
  'devicon-eslint-original-wordmark colored',
  'devicon-eslint-plain colored',
  'devicon-eslint-plain-wordmark colored',
  'devicon-express-original colored',
  'devicon-express-original-wordmark colored',
  'devicon-facebook-plain colored',
  'devicon-facebook-original colored',
  'devicon-feathersjs-original colored',
  'devicon-figma-plain colored',
  'devicon-filezilla-plain colored',
  'devicon-filezilla-plain-wordmark colored',
  'devicon-firebase-plain colored',
  'devicon-firebase-plain-wordmark colored',
  'devicon-firefox-plain colored',
  'devicon-firefox-plain-wordmark colored',
  'devicon-flask-original colored',
  'devicon-flask-original-wordmark colored',
  'devicon-flask-plain colored',
  'devicon-flask-plain-wordmark colored',
  'devicon-flutter-plain colored',
  'devicon-foundation-plain colored',
  'devicon-foundation-plain-wordmark colored',
  'devicon-fsharp-plain colored',
  'devicon-gatling-plain colored',
  'devicon-gatling-plain-wordmark colored',
  'devicon-gatsby-plain colored',
  'devicon-gatsby-plain-wordmark colored',
  'devicon-rect-plain colored',
  'devicon-gcc-plain colored',
  'devicon-gentoo-plain-wordmark colored',
  'devicon-gentoo-plain colored',
  'devicon-gimp-plain colored',
  'devicon-git-plain colored',
  'devicon-git-plain-wordmark colored',
  'devicon-github-original colored',
  'devicon-github-original-wordmark colored',
  'devicon-github-plain colored',
  'devicon-gitlab-plain colored',
  'devicon-gitlab-plain-wordmark colored',
  'devicon-gitter-plain colored',
  'devicon-gitter-plain-wordmark colored',
  'devicon-go-original-wordmark colored',
  'devicon-go-plain colored',
  'devicon-go-line colored',
  'devicon-go-plain-wordmark colored',
  'devicon-google-plain colored',
  'devicon-google-plain-wordmark colored',
  'devicon-google-original colored',
  'devicon-google-original-wordmark colored',
  'devicon-googlecloud-plain colored',
  'devicon-googlecloud-plain-wordmark colored',
  'devicon-gradle-plain colored',
  'devicon-gradle-plain-wordmark colored',
  'devicon-grafana-original colored',
  'devicon-grafana-original-wordmark colored',
  'devicon-grafana-plain colored',
  'devicon-grafana-plain-wordmark colored',
  'devicon-grails-plain colored',
  'devicon-graphql-plain colored',
  'devicon-graphql-plain-wordmark colored',
  'devicon-groovy-plain colored',
  'devicon-grunt-plain colored',
  'devicon-grunt-plain-wordmark colored',
  'devicon-grunt-line colored',
  'devicon-grunt-line-wordmark colored',
  'devicon-gulp-plain colored',
  'devicon-godot-plain colored',
  'devicon-godot-plain-wordmark colored',
  'devicon-haskell-plain colored',
  'devicon-haskell-plain-wordmark colored',
  'devicon-handlebars-plain colored',
  'devicon-handlebars-plain-wordmark colored',
  'devicon-haxe-plain colored',
  'devicon-heroku-original colored',
  'devicon-heroku-original-wordmark colored',
  'devicon-heroku-plain colored',
  'devicon-heroku-plain-wordmark colored',
  'devicon-heroku-line colored',
  'devicon-heroku-line-wordmark colored',
  'devicon-heroku-original colored',
  'devicon-heroku-original-wordmark colored',
  'devicon-html5-plain colored',
  'devicon-html5-plain-wordmark colored',
  'devicon-hugo-plain colored',
  'devicon-hugo-plain-wordmark colored',
  'devicon-ie10-original colored',
  'devicon-ie10-plain colored',
  'devicon-ifttt-original colored',
  'devicon-ifttt-plain colored',
  'devicon-illustrator-plain colored',
  'devicon-illustrator-line colored',
  'devicon-inkscape-plain colored',
  'devicon-inkscape-plain-wordmark colored',
  'devicon-intellij-plain colored',
  'devicon-intellij-plain-wordmark colored',
  'devicon-ionic-original colored',
  'devicon-ionic-original-wordmark colored',
  'devicon-jamstack-original colored',
  'devicon-jamstack-plain-wordmark colored',
  'devicon-jamstack-plain colored',
  'devicon-jasmine-plain colored',
  'devicon-jasmine-plain-wordmark colored',
  'devicon-java-plain colored',
  'devicon-java-plain-wordmark colored',
  'devicon-javascript-plain colored',
  'devicon-jeet-plain colored',
  'devicon-jeet-plain-wordmark colored',
  'devicon-jest-plain colored',
  'devicon-jenkins-line colored',
  'devicon-jenkins-plain colored',
  'devicon-jetbrains-plain colored',
  'devicon-jira-plain colored',
  'devicon-jira-plain-wordmark colored',
  'devicon-jquery-plain colored',
  'devicon-jquery-plain-wordmark colored',
  'devicon-julia-plain colored',
  'devicon-julia-plain-wordmark colored',
  'devicon-jupyter-plain colored',
  'devicon-jupyter-plain-wordmark colored',
  'devicon-kaggle-original colored',
  'devicon-kaggle-original-wordmark colored',
  'devicon-kaggle-plain colored',
  'devicon-kaggle-plain-wordmark colored',
  'devicon-karma-plain colored',
  'devicon-kotlin-plain colored',
  'devicon-kotlin-plain-wordmark colored',
  'devicon-knockout-plain-wordmark colored',
  'devicon-krakenjs-plain colored',
  'devicon-krakenjs-plain-wordmark colored',
  'devicon-kubernetes-plain colored',
  'devicon-kubernetes-plain-wordmark colored',
  'devicon-labview-plain colored',
  'devicon-labview-plain-wordmark colored',
  'devicon-laravel-plain colored',
  'devicon-laravel-plain-wordmark colored',
  'devicon-latex-original colored',
  'devicon-latex-plain colored',
  'devicon-less-plain-wordmark colored',
  'devicon-linkedin-plain colored',
  'devicon-linkedin-plain-wordmark colored',
  'devicon-lua-plain colored',
  'devicon-lua-plain-wordmark colored',
  'devicon-linux-plain colored',
  'devicon-materialui-plain colored',
  'devicon-matlab-plain colored',
  'devicon-matlab-line colored',
  'devicon-magento-original colored',
  'devicon-magento-original-wordmark colored',
  'devicon-magento-line colored',
  'devicon-markdown-original colored',
  'devicon-markdown-plain colored',
  'devicon-maya-plain colored',
  'devicon-maya-plain-wordmark colored',
  'devicon-meteor-plain colored',
  'devicon-meteor-plain-wordmark colored',
  'devicon-minitab-plain colored',
  'devicon-mocha-plain colored',
  'devicon-modx-plain colored',
  'devicon-modx-plain-wordmark colored',
  'devicon-mongodb-plain colored',
  'devicon-mongodb-plain-wordmark colored',
  'devicon-moodle-plain colored',
  'devicon-moodle-plain-wordmark colored',
  'devicon-msdos-line colored',
  'devicon-mysql-plain colored',
  'devicon-mysql-plain-wordmark colored',
  'devicon-neo4j-plain colored',
  'devicon-neo4j-plain-wordmark colored',
  'devicon-nestjs-plain colored',
  'devicon-nestjs-plain-wordmark colored',
  'devicon-networkx-original colored',
  'devicon-nextjs-original colored',
  'devicon-nextjs-plain colored',
  'devicon-nextjs-line colored',
  'devicon-nextjs-original-wordmark colored',
  'devicon-nextjs-plain-wordmark colored',
  'devicon-nextjs-plain colored',
  'devicon-nextjs-plain-wordmark colored',
  'devicon-nginx-original colored',
  'devicon-nginx-original-wordmark colored',
  'devicon-nginx-plain colored',
  'devicon-nginx-plain-wordmark colored',
  'devicon-nginx-original-wordmark colored',
  'devicon-nginx-plain colored',
  'devicon-nginx-plain-wordmark colored',
  'devicon-nixos-plain colored',
  'devicon-nixos-plain-wordmark colored',
  'devicon-nodejs-plain colored',
  'devicon-nodejs-plain-wordmark colored',
  'devicon-nodewebkit-plain colored',
  'devicon-nodewebkit-plain-wordmark colored',
  'devicon-nodewebkit-line colored',
  'devicon-nodewebkit-line-wordmark colored',
  'devicon-npm-original-wordmark colored',
  'devicon-nuget-original colored',
  'devicon-nuget-original-wordmark colored',
  'devicon-numpy-original colored',
  'devicon-numpy-original-wordmark colored',
  'devicon-numpy-plain colored',
  'devicon-nuxtjs-plain colored',
  'devicon-nuxtjs-plain-wordmark colored',
  'devicon-objectivec-plain colored',
  'devicon-opera-plain colored',
  'devicon-opera-plain-wordmark colored',
  'devicon-ocaml-plain colored',
  'devicon-ocaml-plain-wordmark colored',
  'devicon-openal-plain colored',
  'devicon-opengl-plain colored',
  'devicon-opensuse-plain colored',
  'devicon-opensuse-plain-wordmark colored',
  'devicon-oracle-original colored',
  'devicon-oracle-plain colored',
  'devicon-pandas-original colored',
  'devicon-pandas-original-wordmark colored',
  'devicon-pandas-plain colored',
  'devicon-pandas-plain-wordmark colored',
  'devicon-perl-plain colored',
  'devicon-phalcon-plain colored',
  'devicon-photoshop-plain colored',
  'devicon-photoshop-line colored',
  'devicon-php-plain colored',
  'devicon-phpstorm-plain colored',
  'devicon-phpstorm-plain-wordmark colored',
  'devicon-podman-plain colored',
  'devicon-podman-plain-wordmark colored',
  'devicon-polygon-plain colored',
  'devicon-postgresql-plain colored',
  'devicon-postgresql-plain-wordmark colored',
  'devicon-premierepro-plain colored',
  'devicon-processing-plain colored',
  'devicon-processing-plain-wordmark colored',
  'devicon-protractor-plain colored',
  'devicon-protractor-plain-wordmark colored',
  'devicon-putty-plain colored',
  'devicon-pycharm-plain colored',
  'devicon-pycharm-plain-wordmark colored',
  'devicon-python-plain colored',
  'devicon-python-plain-wordmark colored',
  'devicon-pytorch-original colored',
  'devicon-pytorch-plain-wordmark colored',
  'devicon-pytorch-plain colored',
  'devicon-raspberrypi-line colored',
  'devicon-raspberrypi-line-wordmark colored',
  'devicon-phoenix-plain colored',
  'devicon-phoenix-plain-wordmark colored',
  'devicon-qt-original colored',
  'devicon-qt-plain colored',
  'devicon-r-original colored',
  'devicon-r-plain colored',
  'devicon-rails-plain colored',
  'devicon-rails-plain-wordmark colored',
  'devicon-react-original colored',
  'devicon-react-original-wordmark colored',
  'devicon-react-plain colored',
  'devicon-react-plain-wordmark colored',
  'devicon-redhat-plain colored',
  'devicon-redhat-plain-wordmark colored',
  'devicon-redis-plain colored',
  'devicon-redis-plain-wordmark colored',
  'devicon-redux-original colored',
  'devicon-redux-plain colored',
  'devicon-rocksdb-plain colored',
  'devicon-ruby-plain colored',
  'devicon-ruby-plain-wordmark colored',
  'devicon-rubymine-plain colored',
  'devicon-rubymine-plain-wordmark colored',
  'devicon-rust-plain colored',
  'devicon-safari-plain colored',
  'devicon-safari-plain-wordmark colored',
  'devicon-safari-line-wordmark colored',
  'devicon-safari-line colored',
  'devicon-salesforce-plain colored',
  'devicon-sdl-plain colored',
  'devicon-rstudio-plain colored',
  'devicon-sass-original colored',
  'devicon-sass-plain colored',
  'devicon-scala-plain colored',
  'devicon-scala-plain-wordmark colored',
  'devicon-selenium-original colored',
  'devicon-selenium-plain colored',
  'devicon-sequelize-plain colored',
  'devicon-sequelize-plain-wordmark colored',
  'devicon-sequelize-plain colored',
  'devicon-sequelize-plain-wordmark colored',
  'devicon-shopware-original colored',
  'devicon-shopware-original-wordmark colored',
  'devicon-shotgrid-plain colored',
  'devicon-shotgrid-original-wordmark colored',
  'devicon-shotgrid-plain-wordmark colored',
  'devicon-sketch-line colored',
  'devicon-sketch-line-wordmark colored',
  'devicon-slack-plain colored',
  'devicon-slack-plain-wordmark colored',
  'devicon-socketio-original colored',
  'devicon-socketio-original-wordmark colored',
  'devicon-socketio-plain colored',
  'devicon-socketio-plain-wordmark colored',
  'devicon-solidity-plain colored',
  'devicon-sourcetree-original colored',
  'devicon-sourcetree-original-wordmark colored',
  'devicon-sourcetree-plain colored',
  'devicon-sourcetree-plain-wordmark colored',
  'devicon-spring-plain colored',
  'devicon-spring-plain-wordmark colored',
  'devicon-spss-plain colored',
  'devicon-sqlalchemy-plain colored',
  'devicon-sqlalchemy-original-wordmark colored',
  'devicon-sqlalchemy-plain-wordmark colored',
  'devicon-sqlite-plain colored',
  'devicon-sqlite-plain-wordmark colored',
  'devicon-subversion-original colored',
  'devicon-subversion-plain colored',
  'devicon-microsoftsqlserver-plain colored',
  'devicon-microsoftsqlserver-plain-wordmark colored',
  'devicon-ssh-original colored',
  'devicon-ssh-original-wordmark colored',
  'devicon-ssh-plain colored',
  'devicon-ssh-plain-wordmark colored',
  'devicon-stylus-original colored',
  'devicon-svelte-plain colored',
  'devicon-svelte-plain-wordmark colored',
  'devicon-swift-plain colored',
  'devicon-swift-plain-wordmark colored',
  'devicon-symfony-original colored',
  'devicon-symfony-original-wordmark colored',
  'devicon-symfony-plain colored',
  'devicon-symfony-plain-wordmark colored',
  'devicon-storybook-plain colored',
  'devicon-storybook-plain-wordmark colored',
  'devicon-tailwindcss-original-wordmark colored',
  'devicon-tailwindcss-plain colored',
  'devicon-tensorflow-original colored',
  'devicon-tensorflow-original-wordmark colored',
  'devicon-tensorflow-line colored',
  'devicon-tensorflow-line-wordmark colored',
  'devicon-terraform-plain colored',
  'devicon-terraform-plain-wordmark colored',
  'devicon-threejs-original colored',
  'devicon-threejs-original-wordmark colored',
  'devicon-tomcat-line colored',
  'devicon-tomcat-line-wordmark colored',
  'devicon-tortoisegit-plain colored',
  'devicon-tortoisegit-line colored',
  'devicon-towergit-plain colored',
  'devicon-towergit-plain-wordmark colored',
  'devicon-travis-plain colored',
  'devicon-travis-plain-wordmark colored',
  'devicon-thealgorithms-plain colored',
  'devicon-thealgorithms-plain-wordmark colored',
  'devicon-trello-plain colored',
  'devicon-trello-plain-wordmark colored',
  'devicon-twitter-original colored',
  'devicon-twitter-plain colored',
  'devicon-typescript-plain colored',
  'devicon-typescript-original colored',
  'devicon-typo3-plain colored',
  'devicon-typo3-plain-wordmark colored',
  'devicon-ubuntu-plain colored',
  'devicon-ubuntu-plain-wordmark colored',
  'devicon-unity-original colored',
  'devicon-unity-original-wordmark colored',
  'devicon-unix-original colored',
  'devicon-unrealengine-original colored',
  'devicon-unrealengine-original-wordmark colored',
  'devicon-unrealengine-plain colored',
  'devicon-unrealengine-plain-wordmark colored',
  'devicon-uwsgi-plain colored',
  'devicon-vagrant-plain colored',
  'devicon-vagrant-plain-wordmark colored',
  'devicon-vim-plain colored',
  'devicon-visualstudio-plain colored',
  'devicon-visualstudio-plain-wordmark colored',
  'devicon-vuejs-plain colored',
  'devicon-vuejs-plain-wordmark colored',
  'devicon-vuejs-line colored',
  'devicon-vuejs-line-wordmark colored',
  'devicon-vuestorefront-plain colored',
  'devicon-vscode-plain colored',
  'devicon-vscode-plain-wordmark colored',
  'devicon-webflow-original colored',
  'devicon-weblate-plain colored',
  'devicon-weblate-plain-wordmark colored',
  'devicon-webpack-plain colored',
  'devicon-webpack-plain-wordmark colored',
  'devicon-webstorm-plain colored',
  'devicon-webstorm-plain-wordmark colored',
  'devicon-windows8-original colored',
  'devicon-windows8-original-wordmark colored',
  'devicon-windows8-plain colored',
  'devicon-windows8-plain-wordmark colored',
  'devicon-woocommerce-plain colored',
  'devicon-woocommerce-plain-wordmark colored',
  'devicon-wordpress-plain colored',
  'devicon-wordpress-plain-wordmark colored',
  'devicon-xamarin-original colored',
  'devicon-xamarin-original-wordmark colored',
  'devicon-xamarin-plain colored',
  'devicon-xamarin-plain-wordmark colored',
  'devicon-xcode-plain colored',
  'devicon-xd-plain colored',
  'devicon-xd-line colored',
  'devicon-yarn-plain colored',
  'devicon-yarn-plain-wordmark colored',
  'devicon-yii-plain colored',
  'devicon-yii-plain-wordmark colored',
  'devicon-yunohost-plain colored',
  'devicon-zend-plain colored',
  'devicon-zend-plain-wordmark colored',
  'devicon-zig-original colored',
  'devicon-zig-plain-wordmark colored',
  'devicon-zig-plain colored',
  'devicon-pytest-plain colored',
  'devicon-pytest-plain-wordmark colored',
  'devicon-opencv-plain colored',
  'devicon-opencv-plain-wordmark colored',
  'devicon-fastapi-plain colored',
  'devicon-fastapi-plain-wordmark colored',
  'devicon-k3s-original colored',
  'devicon-k3s-plain-wordmark colored',
  'devicon-k3s-plain colored',
  'devicon-packer-original colored',
  'devicon-packer-original-wordmark colored',
  'devicon-packer-plain colored',
  'devicon-packer-plain-wordmark colored',
  'devicon-anaconda-original colored',
  'devicon-anaconda-original-wordmark colored',
  'devicon-anaconda-plain colored',
  'devicon-anaconda-plain-wordmark colored',
  'devicon-rspec-original colored',
  'devicon-rspec-original-wordmark colored',
  'devicon-rspec-plain colored',
  'devicon-rspec-plain-wordmark colored',
  'devicon-argocd-plain colored',
  'devicon-argocd-plain-wordmark colored',
  'devicon-prometheus-original colored',
  'devicon-prometheus-original-wordmark colored',
  'devicon-blender-original colored',
  'devicon-blender-original-wordmark colored',
  'devicon-dropwizard-plain colored',
  'devicon-vuetify-line colored',
  'devicon-vuetify-plain colored',
  'devicon-fedora-plain colored',
].sort();
